Remove unnecessary this qualifier
youngmonkeys/ezyfox-server-flutter-client pull request #15
Opened 2023-09-08 17:10 UTC by namanh11611

### What is the purpose of this pull request?
Based on this lint warning: https://dart.dev/tools/linter-rules/unnecessary_this, I want to remove all unnecessary this qualifier.

### When do you want to merge?
ASAP

2023-09-09 09:20 UTC, tvd12 requested changes
Anh đã test ok, nhưng có 1 comment em xem có cần sửa ko nhé.

2023-09-09 09:20 UTC, tvd12 commented on lib/ezy_proxy.dart
> +            "there is no handler for method: ${call.method}, ignore it");
```dart
EzyLogger.warn(
  "there is no handler for method: ${call.method}, ignore it"
);
```

2023-09-09 16:55 UTC, namanh11611 commented on lib/ezy_proxy.dart
> +            "there is no handler for method: ${call.method}, ignore it");
Em dùng auto format nên nó tự xuống dòng như vậy.
Trong Flutter thì để auto xuống dòng theo format của anh, em sẽ thêm dấu phẩy ở cuối dòng.

2023-09-10 04:04 UTC, tvd12 approved these changes
LGTM

2023-09-10 04:04 UTC, merged